# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: npm install -g arlocal
    command: npx arlocal
  - init: yarn
    command: |
      export CLIENT_URL="$(gp url 35729)/livereload.js?snipver=1&port=443"
      yarn dev

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 5000
    onOpen: open-browser
    visibility: public
  - port: 35729
    onOpen: ignore
  - port: 1984
    onOpen: ignore
    visibility: public
